### ISSUE TITLE
great project,Can I imitate your project and recreate the new project?

### ISSUE THREAD

**Issue by yarnbyte** [junglestory/xmpp-ionic3#1]
In ionic3,I can achieve private chat by modifying your project,but when I create a new project and copy your code, I can only send message, can't get the message,i dont know why...maybe  handle adding failure,so,can you tell me the detailed steps you have created for the project?thank you so much!!!

If you still have problems, please read the below post. 
https://junglestory.github.io/Ionic3-xmpp/

**Comment by junglestory** [comment]
If you still have problems, read this post.
https://junglestory.github.io/Ionic3-xmpp/

**Comment by junglestory** [comment]
If you still have problems, please read the below post. 
https://junglestory.github.io/Ionic3-xmpp/
